import csv
import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT = os.path.join(SCRIPT_DIR, 'Customers PAR Status.csv')
OUTPUT_PATH = os.path.join(SCRIPT_DIR, '..', 'src', 'data', 'customers.ts')

def normalize_status(raw: str) -> str:
    s = raw.strip().upper()
    if not s: return 'ONTIME'
    
    if any(x in s for x in ['ONTIME', 'ON TIME', 'ON-TIME']): return 'ONTIME'
    if '90' in s: return 'PAR 90+'
    if '60' in s or '61' in s: return 'PAR 61-90'
    if '30' in s or '31' in s: return 'PAR 31-60'
    if '1' in s or '1-30' in s: return 'PAR 1-30'
    
    return 'ONTIME'

def convert():
    if not os.path.exists(INPUT):
        print(f"Error: {INPUT} not found. Please place the CSV file in the scripts/ folder.")
        return

    rows = []
    with open(INPUT, encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        try:
            raw_headers = next(reader)
        except StopIteration:
            return
            
        # Deduplicate headers
        headers = []
        counts = {}
        for h in raw_headers:
            h = h.strip()
            if h in counts:
                counts[h] += 1
                headers.append(f"{h}_{counts[h]}")
            else:
                counts[h] = 1
                headers.append(h)
                
        # Now read the rest as dicts
        dict_reader = csv.DictReader(f, fieldnames=headers)
        for i, row in enumerate(dict_reader):
            obj = {
                'contractRef': row.get('Contract reference', '').strip(),
                'name': row.get('Name', '').strip(),
                'phone': row.get('Phone numbers', '').strip(),
                'phone2': row.get('Phone numbers_2', '').strip(),
                'area': row.get('Area', '').strip(),
                'parStatus': normalize_status(row.get('PAR Status', '').strip()),
                'leadGenerate': row.get('Lead Generate', '').strip(),
                'leadGenerateName': row.get('Lead Generate Name', '').strip(),
                'lat': 0.0,
                'lon': 0.0,
            }
            
            lat_str = row.get('Latitude', '').strip()
            lon_str = row.get('Longitude', '').strip()
            if lat_str:
                try: obj['lat'] = float(lat_str)
                except ValueError: pass
            if lon_str:
                try: obj['lon'] = float(lon_str)
                except ValueError: pass
                
            rows.append(obj)

    lines = [
        "// ─────────────────────────────────────────────",
        "// WEEKLY DATA FILE — generated by csv_to_ts.py",
        "// ─────────────────────────────────────────────",
        "",
        "import type { Customer } from '../types/par'",
        "",
        "export const WEEK_LABEL = 'W13 · Mar 2026'",
        "",
        "export const CUSTOMERS: Customer[] = ["
    ]
    for row in rows:
        lines.append('  ' + json.dumps(row, ensure_ascii=False) + ',')
    lines.append(']')

    # ensure dir exists just in case
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f'Done — {len(rows)} customers written to src/data/customers.ts')

if __name__ == '__main__':
    convert()

